In [1]:
from DS_WCS_projections import *
import numpy as np
from astropy.coordinates import SkyCoord
from astropy import units as u

In [2]:
c_wcs = custom_wcs(194.9356, 28.0256)

/home/rt2122/L/git/data-segmentation-2/modules/DS_WCS_projections.py:39: RuntimeWarning: cdelt will be ignored since cd is present
  w1.wcs.cdelt = w.wcs.cdelt[:2]


In [3]:
c_wcs.wcs

       flag: 137
      naxis: 2
      crpix: 0x5576726cae70
               1024.5       1024.5    
         pc: 0x557671a07cf0
    pc[0][]:  -0.0011111    0.0000    
    pc[1][]:   0.0000       0.0011111 
      cdelt: 0x5576726a12f0
               1.0000       1.0000    
      crval: 0x557671dd17c0
               194.94       28.026    
      cunit: 0x5576725456a0
             "deg"
             "deg"
      ctype: 0x5576725eb210
             "RA---TAN"
             "DEC--TAN"
    lonpole: 180.000000
    latpole: 28.025600
    restfrq: 0.000000
    restwav: 0.000000
        npv: 1
     npvmax: 64
         pv: 0x5576726ca9f0
               2   0   0.0000    
        nps: 0
     npsmax: 8
         ps: 0x5576726cd1a0
         cd: 0x55767266db20
    cd[0][]:  -0.0011111    0.0000    
    cd[1][]:   0.0000       0.0011111 
      crota: 0x5576726cd430
               0.0000       0.0000    
     altlin: 2
     velref: 0
        alt: ' '
     colnum: 0
      colax: 0x5576726cd450
              

In [5]:
c_wcs.wcs.crpix

array([128.5, 128.5,   0. ])

In [42]:
pixels = np.array([[0, 0], [128, 128]], dtype=int)

In [43]:
pixels_t = c_wcs.all_pix2world(pixels[:, 0], pixels[:, 1], [0, 0], 0)

In [44]:
pixels_t[0]

array([195.09587421, 194.93497064])

In [45]:
sc = SkyCoord(ra=pixels_t[0]*u.degree, dec=pixels_t[1]*u.degree, frame='icrs')
sc[0].separation(sc[1]).degree

0.20113177899585538

In [16]:
c_wcs.wcs.cd

array([[-0.00111111,  0.        ,  0.        ],
       [ 0.        ,  0.00111111,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [20]:
0.00111111 * 360

0.3999996

In [6]:
o_wcs = find_nearest_tile(194.9356, 28.0256)

/home/rt2122/L/git/data-segmentation-2/modules/DS_WCS_projections.py:19: RuntimeWarning: cdelt will be ignored since cd is present
  w.wcs.cdelt = line['CDELT']


In [29]:
o_wcs.wcs.cd

array([[-0.00076389,  0.        ],
       [ 0.        ,  0.00076389]])

In [30]:
180 * 0.00076389

0.13750020000000002

In [41]:
pixels = np.array([[0, 0], [128, 128]], dtype=int)
pixels_t = c_wcs.all_pix2world(pixels[:, 0], pixels[:, 1], [0, 0], 0)
sc = SkyCoord(ra=pixels_t[0]*u.degree, dec=pixels_t[1]*u.degree, frame='icrs')
sc[0].separation(sc[1]).degree

0.20113177899585538

In [32]:
o_wcs.wcs.cdelt

<ipython-input-32-6fe1acba437c>:1: RuntimeWarning: cdelt will be ignored since cd is present
  o_wcs.wcs.cdelt


array([1., 1.])

In [33]:
c_wcs.wcs.cdelt

<ipython-input-33-1f78aef4318f>:1: RuntimeWarning: cdelt will be ignored since cd is present
  c_wcs.wcs.cdelt


array([1., 1., 1.])

In [35]:
o_wcs.wcs

       flag: 137
      naxis: 2
      crpix: 0x561f192cb5c0
               1024.5       1024.5    
         pc: 0x561f1925b820
    pc[0][]:  -0.00076389   0.0000    
    pc[1][]:   0.0000       0.00076389
      cdelt: 0x561f1908ee10
               1.0000       1.0000    
      crval: 0x561f192cb600
               195.43       28.774    
      cunit: 0x561f192935f0
             "deg"
             "deg"
      ctype: 0x561f193d6780
             "RA---TAN"
             "DEC--TAN"
    lonpole: 180.000000
    latpole: 28.774444
    restfrq: 0.000000
    restwav: 0.000000
        npv: 1
     npvmax: 64
         pv: 0x561f1936abe0
               2   0   0.0000    
        nps: 0
     npsmax: 8
         ps: 0x561f19366c10
         cd: 0x561f19366ea0
    cd[0][]:  -0.00076389   0.0000    
    cd[1][]:   0.0000       0.00076389
      crota: 0x561f19291b90
               0.0000       0.0000    
     altlin: 2
     velref: 0
        alt: ' '
     colnum: 0
      colax: 0x561f19293690
              

In [38]:
180 * 0.00076389 

0.13750020000000002

In [16]:
def dist_from_center(wcs_proj):
    pixels = np.array([[0, wcs_proj.wcs.crpix[0]], wcs_proj.wcs.crpix], dtype=int)
    pixels_t = c_wcs.all_pix2world(pixels[:, 0], pixels[:, 1], 0)
    sc = SkyCoord(ra=pixels_t[0]*u.degree, dec=pixels_t[1]*u.degree, frame='icrs')
    return sc[0].separation(sc[1]).degree

In [19]:
dist_from_center(c_wcs)

1.1376284753016908

In [7]:
dist_from_center(o_wcs)

1.6086385730354449

In [12]:
c_wcs.wcs.cd

array([[-0.00076389,  0.        ],
       [ 0.        ,  0.00076389]])

In [13]:
o_wcs.wcs.cd

array([[-0.00076389,  0.        ],
       [ 0.        ,  0.00076389]])

In [18]:
c_wcs.wcs.cd /= 2